USE lesson3;

INSERT INTO meal (id, title, description, location, `when`, max_reservations, price, created_date)
VALUES 
(2,
'Classic zucchini slice',
'This particular zucchini slice recipe is without doubt the best we’ve tasted (and we’ve tried a lot over the years). Originally submitted by Artarmon Public School in Sydney, it not only has the endorsements of more than 1,000 reviewers, but it’s also been tasted by school kids and the taste team’s tough food critics alike.', 
'Australia',
'2025-06-05',
156,
30.00,
'2025-06-05'),
(3, 
'Creamy French onion chicken pasta bake',
'Let’s face it - it’s a cheesy pasta bake – and we all love that, but our recipe also makes use of pre-prepared ingredients that add so much flavour with very little effort. Not only the packet of French onion soup mix, but we also use supermarket-bought bbq chicken and three cheese mix. We also love that it can be assembled earlier on in the day and cooked just before serving. And, despite being a bake, there’s no turning on the oven, instead a short stint under the grill is all it needs to become bubbly and golden.',
'France',
'2025-08-02',
156,
10.00,
'2025-06-05'),
(4,
'Fried rice',
'In this super simple egg fried rice recipe we use pantry and fridge staples, but the beauty of basic fried rice recipes is that you can always adjust the ingredients based on what you happen to have on hand at any given time. The real secret here is to use a large fry pan or wok on a very high heat so the rice is fried and golden, rather than steamed or gluggy. Cooking it this way ensures the fried rice still has bite and absorbs the lovely flavours of the bacon and soy, without resembling a risotto!',
'China',
'2025-10-03',
0,
30.00,
'2025-06-05');

INSERT INTO reservation (id, number_of_guests, meal_id, created_date, contact_phonenumber, contact_name, contact_email) VALUES 
(2, 
12, 
2, 
'2025-06-05', 
'45256842',
'Jens',
'jens@gmail.com'),
(3,
27,
2,
'2025-06-05',
'45867402',
'Natalia',
'natalia@gmail.com'),
(4,
2,
1,
'2025-06-05',
'45506970',
'Karl',
'karl@gmail.com'),
(5,
7,
3,
'2025-06-05',
'45274959',
'Hans',
'hans@gmail.com');

INSERT INTO review (id, title, description, meal_id, stars, created_date) 
VALUES 
(2, 
'Review', 
'It is good, but really spicy', 
4, 
3, 
'2025-05-06'),
(3,
'This is not so good :(',
'This French pasta bake is really creamy. I do not like it :(',
3,
1,
'2025-05-06'),
(4,
'Super!',
'This rice as spicy, as in my homeland! I appreciate that! If I could, I would give 10 out of 5!',
4,
5,
'2025-05-06')